# Generated by Django 3.0.8 on 2020-07-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danhmuc',
            name='chitiet',
            field=models.ManyToManyField(to='sanpham.Thuoctinh', verbose_name='Chon'),
        ),
    ]
