# Generated by Django 3.0.8 on 2020-08-03 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0002_auto_20200731_1400'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thuoctinhdanhmuc',
        ),
    ]
