# Generated by Django 3.0.8 on 2020-08-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0003_delete_thuoctinhdanhmuc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='mota',
            field=models.TextField(verbose_name='Mô tả'),
        ),
    ]
