# Generated by Django 3.0.8 on 2020-08-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('hinh', models.ImageField(null=True, upload_to='slider/', verbose_name='Hình slide')),
                ('hinh_mobile', models.ImageField(null=True, upload_to='slider-m/', verbose_name='Hình slide moblie')),
                ('thutu', models.CharField(choices=[('1', 'Đầu tiên'), ('2', 'Thứ 2'), ('3', 'Thứ 3'), ('4', 'Thứ 4'), ('5', 'Thứ 5'), ('6', 'Thứ 6'), ('7', 'Thứ 7')], default='2', max_length=20, unique=True, verbose_name='Chọn thứ tự hiện thị')),
                ('action', models.BooleanField(default=False, verbose_name='Hiện thị ngoài trang chủ')),
            ],
            options={
                'verbose_name_plural': 'Banner ',
            },
        ),
    ]
