# Generated by Django 3.0.8 on 2020-08-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200803_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tintuc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200, unique=True, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Đường dẫn')),
                ('thumb', models.ImageField(upload_to='tintuc/')),
            ],
        ),
    ]
