# Generated by Django 3.0.8 on 2020-08-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_tintuc'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMucTinTuc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=500, null=True, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(max_length=100, verbose_name='Đường dẫn')),
            ],
            options={
                'verbose_name_plural': 'Danh mục tin tức',
            },
        ),
        migrations.DeleteModel(
            name='Tintuc',
        ),
    ]
