# Generated by Django 3.0.8 on 2020-08-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200806_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tintuc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200, unique=True, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Đường dẫn')),
                ('hinh', models.ImageField(upload_to='tintuc/')),
                ('luotxem', models.IntegerField(default=1)),
                ('mota', models.TextField(blank=True, verbose_name='Mô tả')),
                ('ngaytao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('danhmuc', models.ManyToManyField(to='home.DanhMucTinTuc', verbose_name='Danh mục tin tức')),
            ],
        ),
    ]
