# Generated by Django 3.0.8 on 2020-08-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_tintuc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tintuc',
            options={'verbose_name_plural': 'Tin tức'},
        ),
        migrations.AlterField(
            model_name='danhmuctintuc',
            name='ten',
            field=models.CharField(max_length=500, null=True, unique=True, verbose_name='Tên danh mục'),
        ),
    ]
