# Generated by Django 3.0.8 on 2020-08-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CauHinh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cauhinhseo',
            name='youtube',
            field=models.CharField(default='https://www.youtube.com/channel/UCBNPt04r_cpQncTQ-YT7E5A/', max_length=100),
        ),
        migrations.AlterField(
            model_name='cauhinhseo',
            name='des',
            field=models.TextField(default='Tsunoda việt nam chuyên cung cấp sỉ & lẻ kìm cắt , kìm bấm , kìm điện ,kìm cầm tay các loại  chất lượng ✅Chính hãng ✅Giá rẻ nhất ✅Giao hàng hoả tốc 1-2h ☎️Tư vấn sâu.', max_length=300, verbose_name='Mô tả website'),
        ),
        migrations.AlterField(
            model_name='cauhinhseo',
            name='favico',
            field=models.ImageField(default='/media/logo-1.png', null=True, upload_to='', verbose_name='Favico'),
        ),
        migrations.AlterField(
            model_name='cauhinhseo',
            name='keyword',
            field=models.CharField(default='kìm cắt,các loại kìm,kìm điện,kìm điện đa năng,kìm nhật bản,kìm cắt sắt giá rẻ', help_text='Từ khóa được phân cách bằng dầu phẩy', max_length=300, verbose_name='Từ khóa website'),
        ),
        migrations.AlterField(
            model_name='cauhinhseo',
            name='robots',
            field=models.CharField(choices=[('index,follow', 'Lập chỉ mục trang web (index,follow)'), ('noindex,nofollow', 'Chặn google lập chỉ mục trang web :(noindex,nofollow)')], default='index,follow', help_text='Tùy chỉnh lập chỉ mục trang web với google', max_length=100, verbose_name='Robots'),
        ),
        migrations.AlterField(
            model_name='cauhinhseo',
            name='title',
            field=models.CharField(default='Tsunoda Việt Nam - Thương hiệu dụng cụ kìm hàng đầu Nhật Bản tại Việt Nam', max_length=200, verbose_name='Tiêu đề website'),
        ),
    ]
