# Generated by Django 3.0.8 on 2020-08-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CauHinh', '0002_auto_20200803_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='cauhinhseo',
            name='logo',
            field=models.ImageField(default='https://hatoktools.com/wp-content/uploads/2020/07/logo-1.png', null=True, upload_to='', verbose_name='Logo'),
        ),
    ]
