# Generated by Django 3.0.8 on 2020-08-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CauHinh', '0003_cauhinhseo_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cauhinhseo',
            name='catalog',
            field=models.CharField(default='https://www.youtube.com/channel/UCBNPt04r_cpQncTQ-YT7E5A/', max_length=100),
        ),
        migrations.AlterField(
            model_name='cauhinhseo',
            name='robots',
            field=models.CharField(choices=[('noindex,nofollow', 'Chặn google lập chỉ mục trang web :(noindex,nofollow)'), ('index,follow', 'Lập chỉ mục trang web (index,follow)')], default='index,follow', help_text='Tùy chỉnh lập chỉ mục trang web với google', max_length=100, verbose_name='Robots'),
        ),
    ]
