# Generated by Django 3.0.8 on 2020-08-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CauHinh', '0004_auto_20200805_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='cauhinhseo',
            name='lienhe',
            field=models.CharField(default='https://hatoktools.com/', max_length=100),
        ),
        migrations.AlterField(
            model_name='cauhinhseo',
            name='robots',
            field=models.CharField(choices=[('index,follow', 'Lập chỉ mục trang web (index,follow)'), ('noindex,nofollow', 'Chặn google lập chỉ mục trang web :(noindex,nofollow)')], default='index,follow', help_text='Tùy chỉnh lập chỉ mục trang web với google', max_length=100, verbose_name='Robots'),
        ),
    ]
