# Generated by Django 3.0.8 on 2020-08-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CauHinh', '0005_auto_20200805_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cauhinhseo',
            name='robots',
            field=models.CharField(choices=[('noindex,nofollow', 'Chặn google lập chỉ mục trang web :(noindex,nofollow)'), ('index,follow', 'Lập chỉ mục trang web (index,follow)')], default='index,follow', help_text='Tùy chỉnh lập chỉ mục trang web với google', max_length=100, verbose_name='Robots'),
        ),
        migrations.AlterField(
            model_name='cauhinhseo',
            name='title',
            field=models.CharField(default='Tsunoda Việt Nam', max_length=200, verbose_name='Tiêu đề website'),
        ),
    ]
