# Generated by Django 3.0.8 on 2020-08-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CauHinh', '0009_auto_20200806_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cauhinhseo',
            name='robots',
            field=models.CharField(choices=[('noindex,nofollow', 'Chặn google lập chỉ mục trang web :(noindex,nofollow)'), ('index,follow', 'Lập chỉ mục trang web (index,follow)')], default='index,follow', help_text='Tùy chỉnh lập chỉ mục trang web với google', max_length=100, verbose_name='Robots'),
        ),
    ]
