# Generated by Django 3.0.8 on 2020-08-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CauHinh', '0010_auto_20200807_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='cauhinhseo',
            name='gioithieu',
            field=models.CharField(default='https://hatoktools.com/', max_length=100),
        ),
    ]
